### ISSUE TITLE
Current weather

### ISSUE THREAD

**Issue by hm1234** [edward-shen/MMM-pages#37]
current weather will not load on page one no settings changed just default

**Comment by edward-shen** [comment]
The bug template is there for a reason: it's to help me help you. If you can't provide a clear and concise explanation, ignore the format that I explicitly put in place to help people out, **and** knowingly delete the template, it shows clear lack of respect for my time and efforts and I will refuse to assist you on that premise.

You're free to create a new issue and try again.

**Comment by hm1234** [comment]
@edward-shen hey man sorry. I should have read it through. My apologies.

**Comment by edward-shen** [comment]
I accept your apology. I ask that you just keep in mind that I, like many other authors of open source projects, offer support as a volunteer. While I personally want to support the growth of my work (otherwise I wouldn't be volunteering), this still takes time and effort out of my day to help others, especially on a one-to-one personal basis like this.

As long as you're cognizant of that, I'll be happy to help you. If you still need help, please try and follow the template to the best of your knowledge. We can continue to go from there.
