### ISSUE TITLE
How to use touchscreen to slide?

### ISSUE THREAD

**Issue by MarvellousMili** [edward-shen/MMM-pages#42]
I want this module to slide on the touch screen, I have an IR Frame, but I don't know what to do right.
Plz help me, thank you so much!!

**Comment by edward-shen** [comment]
MMM-pages doesn't provide any way to change the page based on input by itself. This is by design—there are many ways to communicate to the magic mirror and I can't support them all.

I'm not sure if there's anything out there that covers your use case. [MMM-page-indicator](https://github.com/edward-shen/MMM-page-indicator) has a basic feature where you can tap on each page indicator to go to that page, but I'm not aware of anything for swipe gestures.

**Comment by MarvellousMili** [comment]
Got it, I'm now using both these two modules, and they work perfectly. I'll find a way to solve this and when I get there I'll post here

**Comment by edward-shen** [comment]
I'm closing this issue due to old age. Please feel free to reopen this issue if you still have a problem.

Feel free to post your solution here if you do find one.
