### ISSUE TITLE
New Maintainer ? 

### ISSUE THREAD

**Issue by bugsounet** [edward-shen/MMM-pages#69]
Hi @edward-shen,

If you really search a new maintainer for this project and MMM-page-indicator, I'm able to do it !

I have coded some MagicMirror [modules/plugins](https://wiki.bugsounet.fr) and i'm trying to be very responsive with issue

Maybe it's time coding/refact with `MMM-pages` v2 ? :)

@bugsounet

**Comment by edward-shen** [comment]
Hey! Thanks for reaching out. Sorry for the late response, I'm currently on vacation and haven't had time to respond.

Just to confirm, are you looking to take over maintainership for both MMM-pages and MMM-page-indicator?

I'd be happy for you to take over maintainership, but I'd like to just make sure of a few things since this is my first time doing something like this.

Just so we are on the same page on a few logistics:
1. Do you have any intention on changing the license in the future? I'd like to keep things as is (I think both modules are MIT).
2. Are you okay with me giving you write permissions to this repo instead of transferring it to you? I think there are modules that keep track of repos to update, so transferring the repo might cause a lot of problems. I don't plan on touching the repo or stopping you from doing anything, though.

Cheers!

**Comment by bugsounet** [comment]
Hi @edward-shen 

> Just to confirm, are you looking to take over maintainership for both MMM-pages and MMM-page-indicator?

sure I confirm

> Do you have any intention on changing the license in the future? I'd like to keep things as is (I think both modules are MIT).

All of my modules/plugins are in `MIT` license so I will not change it !

> Are you okay with me giving you write permissions to this repo instead of transferring it to you? I think there are modules that keep track of repos to update, so transferring the repo might cause a lot of problems. I don't plan on touching the repo or stopping you from doing anything, though.

Sorry about this but in this case i will not override my rules (my own wiki, own forum, own support)
I prefert that you keep your modules to you :(
So I will just import both modules into my github account and modify/refact it
(naturally, I will not delete your name/nickname in the code part OR in other case, it will be added in `package.json` file)

Good continuation in other project!
@bugsounet
